### ISSUE TITLE
Additional image formats fail WMTS tests.

### ISSUE THREAD

**Issue by jtomaka** [opengeospatial/ets-wmts10#13]
If WMTS service expose image formats that the test system does not understand, the test will fail.
It should not test formats it does not understand. 
In our case it was image/webp and image/jpegxr that were not understood.

**Comment by dstenger** [comment]
Can you provide a test service URL to reproduce the error and to verify a potential fix?

Fix could be implemented as described by @rjmartell.

**Comment by bermud** [comment]
@jtomaka, can you please provide a service URL for further testing?

**Comment by rjmartell** [comment]
The test definition is in wmtsServerGetTileTests.xml. It invokes the function `wmtsFunctions:KVP.GetTile.Valid.Tile.Size` (defined in wmtsFunctions.xml).

**Comment by rjmartell** [comment]
The proposed fix: Check if the image media type (extracted from the Content-Type response header) corresponds to a supported image type (media subtype, which usually matches a file extension, e.g. "png", "jpeg" ). If not, produce a **skip** instead of a fail verdict.

**Comment by rjmartell** [comment]
This function is implemented in a very coarse manner, with 8 nested `<xsl:for-each>` elements! Every invocation sends multiple requests (e.g. 18 requests sent when run against the service at http://192.71.92.21/MapService/wmts.axd/Vmap0WMTS). So if any one request produces a skip verdict then the whole test is marked as skipped even if all the other requests were ok.

**Note**: The function is called twice: from `wmts:Server.KVP.GET.GetTile.Valid.Tile.Size` and from 
`wmts:Server.KVP.POST.GetTile.Valid.Tile.Size`.

These tests should be restructured such that the image format is a parameter. Then a skip verdict doesn't taint the other results.

**Comment by rjmartell** [comment]
Introduce `wmts:GetTileMatrixByImageFormat` as a subtest that accepts an image media type (format) as an input parameter. It's called once for each supported image format:

    <xsl:for-each select="distinct-values($wmts.capabilities.doc//wmts:Layer/wmts:Format/text())">
      <ctl:call-test name="wmts:GetTileMatrixByImageFormat">
        <ctl:with-param name="image-format" select="." />
