### ISSUE TITLE
Functions with same name appear in wwwFunctions.xml

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/ets-wmts10#20]
There are two functions declared in wwwFunctions.xml with the same name: "wwwFunctions:provokeNotFound". This function is called by the test `Server.KVP.GET.HTTP.Mandatory` (defined in wmtsServerCommonOperationsTests.xml).

Function names should be unique; otherwise invocation is problematic.

**Comment by dbretschneider** [comment]
There was a function which references itself:
```xml
	<ctl:function name="wwwFunctions:provokeNotFound">
		<ctl:param name="capabilitiesURL">/wmts:Capabilities/ows:OperationsMetadata/ows:Operation[@name='GetCapabilities']/ows:DCP/ows:HTTP/ows:Get/@xlink:href</ctl:param>
		<ctl:param name="method">get|post</ctl:param>
		<ctl:description>Provoke an HTTP 404 error and test whether the server returns that status code.</ctl:description>
		<ctl:code>
			<xsl:value-of select="wwwFunctions:provokeNotFound($capabilitiesURL, $method, '/nonesuch')"/>
		</ctl:code>
	</ctl:function>
```

I have renamed the function name from ```wwwFunctions:provokeNotFound``` to ```wwwFunctions:provokeNotExistentService```.

Pull request: https://github.com/opengeospatial/ets-wmts10/pull/23

**Comment by segoerke** [comment]
https://github.com/opengeospatial/ets-wmts10/pull/23
