### ISSUE TITLE
Test memory issues

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wmts10#22]
When executing KVP for this
http://cite.lat-lon.de/deegree-webservices-3.4-pre15/services/wmts?service=WMTS&request=GetCapabilities

The test console stops (freezes) in this test:

```
Testing wmts:Server.KVP.GET.GetFeatureInfo.Mandatory type MandatoryIfImplemented in Test Mode with defaultResult Pass (s0036/server.profile.kvp.get/d4033e6040_1/d4033e7188_1)...             Context: wmts:main 
```

The logs report the following:
```
SEVERE: The web application [/teamengine] created a ThreadLocal with key of type [com.sun.jersey.core.impl.provider.xml.ThreadLocalSingletonContextProvider$1] (value [com.sun.jersey.core.impl.provider.xml.ThreadLocalSingletonContextProvider$1@1cade899]) and a value of type [net.sf.saxon.TransformerFactoryImpl] (value [net.sf.saxon.TransformerFactoryImpl@4c1784cb]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Mar 05, 2015 7:56:13 PM org.apache.catalina.core.StandardContext reload
INFO: Reloading Context with name [/teamengine] is completed
```

**Comment by dbretschneider** [comment]
I have executed the actual ```ets-wmts10``` test suite (```master```) against [deegree 3.4-pre15](http://cite.lat-lon.de/deegree-webservices-3.4-pre15/services/wmts?service=WMTS&request=GetCapabilities). The test took 15 minutes for all steps without freezing.

**Comment by dbretschneider** [comment]
I've selected all profiles and execute all operations:

![selected_profiles](https://cloud.githubusercontent.com/assets/3016561/6866271/cf880a62-d476-11e4-9d9f-bc5aa23dde65.png)

![test_group_selection](https://cloud.githubusercontent.com/assets/3016561/6866276/dbc458d0-d476-11e4-8bf1-fae5f7e34a19.png)

But only HTTP Get was executed in 15 minutes. All other profiles are not supported.

**Comment by dbretschneider** [comment]
@bermud: Can we close this issue or is it occurred again?

**Comment by bermud** [comment]
In the current TE beta the test finishes successfully. Still some errors with the server implementation.
