### ISSUE TITLE
wmts:Server.RESTful.HTTP.Mandatory does not work with self-declaring service

### ISSUE THREAD

**Issue by matsoo** [opengeospatial/ets-wmts10#24]
The wmts:Server.RESTful.HTTP.Mandatory test is supposed to test a invalid url and verify that the response is a 404 http code, but the url it sends is the base url for the service which we use to return capabilities.

As far as I can tell there is nothing in the WMTS specification that prohibits this (10.1.1 in the specification says any url can be used for ServiceMetadata) and I don't think it is correct to demand this url returns a 404 code. 

The test could probably add a nonesuch parameter as the equivalent KVP test wmts:Server.KVP.GET.HTTP.Mandatory does but it would then be redundant as this is exactly what the test wmts:Server.RESTful.InvalidQueryString does.

**Comment by lgoltz** [comment]
Can you provide the service URL or at least the capabilities document?

**Comment by matsoo** [comment]
Try using the following service:
http://192.71.92.21/MapService/wmts.axd/Vmap0WMTS
This url also returns the capabilities document, which is what causes this problem.

**Comment by lgoltz** [comment]
Thanks, now I understand the problem. As you say adding an nonesuch parameter would be duplicated, but maybe it could be a way to append an invalid path to the url, like: http://192.71.92.21/MapService/wmts.axd/Vmap0WMTS/nonesuch

**Comment by dstenger** [comment]
If an invalid path is appended, the tests
 * Server.RESTful.HTTP.Mandatory
and
 * wmts:Server.RESTful.InvalidQueryString
are doing exactly the same.

After having read the Assertion
{{{
Assertion: 
	A.  TBD: First Draft:   HTTP status code 404
	1.  The request entity is for a non-existent service
	2.  The HTTP status code value is set to 404, corresponding to the message &quot;Not Found&quot;
}}}
I would say that the service name has to be manipulated to a non-existent service in this test.
E.g.: http://192.71.92.21/MapService/wmts.axd/Vmap0WMTSnonesuch

**Comment by bermud** [comment]
@rjmartell, please advise how to better improve the test assertion.

**Comment by rjmartell** [comment]
The test in question lurks in the wmtsServerCommonOperationsTests.xml file. There is no reference to an abstract test case (Annex A of the WMTS 1.0 spec) or any other requirement, so it's unclear what is meant by a "non-existent service".

In the draft test suite description (0.7, 2011-10-31), no assertions are listed for test case [Server.RESTful.HTTP.Mandatory](http://cite.opengeospatial.org/te2/about/wmts/1.0.0/site/ats.html#Server.RESTful.HTTP.Mandatory) (TBD).

__Note__: This document seems to be unrelated to the ATS in Annex A of the WMTS 1.0 spec (OGC 07-057r7)

I suggest dropping this test as irrelevant.

**Comment by rjmartell** [comment]
Clause 10 in the WMTS specification distinguishes three kinds of resources:

* service (ServiceMetadata)
* map tiles (Tile)
* feature info (FeatureInfo)

**Comment by rjmartell** [comment]
Perhaps this can test for an unknown resource: either an unsupported URL or an unsupported media type. Since the purpose of ATC A.3.1.5 mentions a service metadata request and the intent is to elicit a service exception, specify an unsupported media type using the Accept header (see cl. 10.1.1); the response must indicate an error with status code 406 (Not Acceptable).
