### ISSUE TITLE
Conformance Determination: Simple profile

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wmts10#26]
In the overview page
http://cite.opengeospatial.org/te2/about/wmts/1.0.0/site/

It says:
All tests in one or more protocol binding profiles must be selected for conformance certification.

Is this "rule" properly coded/enforced in the test?

**Comment by bermud** [comment]
From our conversation, it seems the result is not machine readable since the profiles are broken into sub reports and there is no check from a parent report that at least one profile is passing so certification can be granted. Maybe this issue is to be fixed as part of the profiles work to be done in testbed 12.

**Comment by bermud** [comment]
What its the core most basic that we can extract from this test?

**Comment by rjmartell** [comment]
See summary on this wiki page: [WMTS-Simple-Profile](/opengeospatial/ets-wmts10/wiki/WMTS-Simple-Profile)

**Comment by bermud** [comment]
Schemas are here:
http://schemas.opengis.net/wmts/1.0/profiles/wmts-simple/
 
issue: the identifiers of the tilematrixsets are fixed to 3 names: WorldWebMercatorQuad, WorldCRS84Quad or InspireCRS84Quad.
 
However; this is NOT a requirement in WMTS simple profile.

**Comment by bermud** [comment]
The minimum, most basic conformance class to get certified is the "Profile: GET binding" as stated in revision 0.7
