### ISSUE TITLE
Schematron to be included in the test

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wmts10#27]
Check that this schematron is included in the test
http://schemas.opengis.net/wmts/1.0/profiles/wmts-simple/

**Comment by dstenger** [comment]
Can you please check if it is possible to include schematrons in this test suite (beware, it is CTL)?

**Comment by keshav-nangare** [comment]
@dstenger 

We can do this implementation as similar to the ets-csw20. Here is the reference: 

https://github.com/opengeospatial/ets-csw202/blob/55137829e03856a11fbe95399adebb0c17d7b5bc/src/main/scripts/ctl/GetCapabilities/CSW-GetCapabilities-GET.xml#L116-L120

**Comment by dstenger** [comment]
The provided Schematron can be used to test the WMTS Simple Profile but not the implementation standard itself (see https://www.ogc.org/standards/wmts).

@ghobona We should check if a test of the simple profile can be integrated into the test suite.

**Comment by ghobona** [comment]
@dstenger 

We should integrate the WMTS Simple Profile into the existing WMTS ETS.

I will ask @keshav-nangare to proceed with the integration.

**Comment by ghobona** [comment]
Discussion on 2020-07-22, @keshav-nangare to add the schematron in a separate test in the WMTS test suite.

**Comment by keshav-nangare** [comment]
@dstenger @ghobona

Following are my findings:

- I faced some issues while loading Schematron referred in the first comment:
  1. The namespace for Schematron currently refers to `http://purl.oclc.org/dsdl/schematron`.
  2. It does not define any phase which can execute the pattern and the element `value-of` is having a problem as below:
`Line 30 - element "sch:value-of" not allowed here; expected the element end-tag, text, element "sch:dir", "sch:emph", "sch:name" or "sch:span" or an element from another namespace`

* I have updated the Schematron as per below which loads successfully.
  1. The namespace should be changed to `http://www.ascc.net/xml/schematron`.
  2. Added the `DefaultPhase` and removed the `value-of` element statement.

Let me know your thought on this.

**Comment by keshav-nangare** [comment]
@dstenger @ghobona 

I have investigated the Schematron issue with ISO namespace and found a problem with our SchematronParser library. Currently, TE `SchematronValidatingParser.java`  using `jing library` to validate Schematron as per investigation it is not supporting the latest ISO Schematron. Also, I found a similar issue(# 258) opened in their GitHub [repository](https://github.com/relaxng/jing-trang).

Should we use different libraries to validate ISO Schematron? What is your opinion on this?

**Comment by ghobona** [comment]
I would suggest creating a separate class called `ISOSchematronValidatingParser.java`, then using [ph-schematron](http://phax.github.io/ph-schematron/) with the new class.

**Comment by dstenger** [comment]
@keshav-nangare Please create a new issue in TEAM Engine tracker and implement an `ISOSchematronValidatingParser` as suggested in comment https://github.com/opengeospatial/ets-wmts10/issues/27#issuecomment-667062051.

**Comment by dstenger** [comment]
ph-schematron uses Saxon-HE. Thus, https://github.com/opengeospatial/teamengine/issues/32 must be solved first.

Alternatively, we can check if there is another schematron library.

**Comment by keshav-nangare** [comment]
The changes for the Schematron are included in the #69 PR.

**Comment by ghobona** [comment]
This issue has been overtaken by events.
