### ISSUE TITLE
Unclear ResourceURL validation

### ISSUE THREAD

**Issue by mcechini** [opengeospatial/ets-wmts10#29]
In the wmts:GetTile.Mandatory.RESTful test, we see all of the test items fail with the following code:

   FAILURE: invalid template
http://gibs.earthdata.nasa.gov/wmts/epsg4326/best/MODIS_Terra_Data_No_Data/default/{Time}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}.png

However, it is not clear why this is invalid.  I don’t see a test that simply does validation of the template, nor are there enough details to know why it is failing.

http://gibs.earthdata.nasa.gov/wmts/epsg4326/best/wmts.cgi?SERVICE=WMTS&REQUEST=GetCapabilities

**Comment by lgoltz** [comment]
The test checks if the resource template contains the following parts:
 * the Id of the current layer
 * {TileMatrixSet}
 * {TileMatrix}
 * {TileRow}
 * the identifier of the dimensions of the current layer in curly brackets

All of them are tested **case sensitive**. I assume the test fails cause of the dimension which has the identifier 'time' but in the template {Time} is set.  

By the way: In the next version all other bindings except GET are removed (see #33).

**Comment by dstenger** [comment]
Closed as test is not part of test suite any more.
