### ISSUE TITLE
Bogus KVP request validation

### ISSUE THREAD

**Issue by mcechini** [opengeospatial/ets-wmts10#30]
For the wmts:Server.RESTful.HTTP.Mandatory test...

A request with the following invalid content:
	service=WMTS&amp;request=GetBOGUS

Should reply as such:
	2.  the response entity is a schema-valid ows:Exception document.
	3.  the response entity contains an exceptionCode attribute value of "InvalidParameterValue".
	4.  the response entity contains a locator attribute value of "request".
	5.  the HTTP status code value is set to 400, corresponding to the message "Bad Request".

... and a request with the following invalid content:
	service=BOGUS&amp;request=GetCapabilities

Should reply as such:
	1.  the request entity service parameter value is "BOGUS".
	2.  the response entity is a schema-valid ows:Exception document.
	3.  the response entity contains an exceptionCode attribute value of "InvalidParameterValue".
	4.  the response entity contains a locator attribute value of "service".
	5.  the HTTP status code value is set to 400, corresponding to the message "Bad Request".

I do not see where in the specification that an exceptionCode of “InvalidParameterValue” is required for an invalid REQUEST value.  “InvalidParameterValue” is referenced as the exceptionCode within the context of a GetCapabilities/GetTile/GetFeatureInfo request.  However, since the REQUEST value is not valid, those rules would not apply directly.  I believe this is possibly an item that would be flagged as missing from the specification.  We currently return an exception code of “OperationNotSupported” based on what we believe should be inherited from Page 71 of the WMS 1.3.0 specification.

I also do not see anything in the specification requiring a specific exceptionCode when the SERVICE value is bogus.  

It seems like there should be a consistent exceptionCode across the W*S services for these cases, as this should apply globally.  Does that exist?

**Comment by dstenger** [comment]
You are probably talking about following tests?
* wmts:Server.KVP.GET.InvalidService
* wmts:Server.KVP.POST.InvalidService
* wmts:Server.XML.POST.InvalidService
* wmts:Server.SOAP.POST.InvalidService

These tests base on OpenGIS Web Service Common Implementation Specification (OGC 06-121r3) being a base document of WMTS 1.0.
Chapter 7.4.1, pp. 22 and table 8, p. 23 describe why an InvalidParameterValue exception is thrown.

**Comment by bermud** [comment]
I agree if the value of a parameter is incorrect then the server should report InvalidParameterValue, 400, Bad request.  These include the parameters SERVICE and REQUEST.

**Comment by mcechini** [comment]
ok, thanks.  it wasn't clear where that requirement was coming from.
