### ISSUE TITLE
Hard coded style and tileMatrixSet identifiers

### ISSUE THREAD

**Issue by vinnakota** [opengeospatial/ets-wmts10#32]
Test engine requires style and tileMatrixSet identifiers to match specific strings. Not all servers allow modifying these values. Is it possible for the test engine to retrieve these values from the WMTS capabilities based on the layer identifier "TransparentNodata"

**Comment by dstenger** [comment]
I agree with you that this is a rigid restriction (of course, it is documented in Test Data section on http://cite.opengeospatial.org/te2/about/wmts/1.0.0/site/).

On the other hand, if a server supports multiple styles and tileMatrixSets, the user cannot control which style and tileMatrixSet is picked (and this is important as there is an expected response, which is described in the Test Data section of the about page).

A possible solution for making the test suite more data independent is to pick the first provided style and tileMatrixSet from capabilities. Those values are then used in all relevant test steps.

**Comment by dstenger** [comment]
Discussed solution: An identifier can be provided via GUI. If none is provided the current mechanism is kept (default identifier).

**Comment by lgoltz** [comment]
From the code side of view I see that the following four tests are requesting the layer _TransparentNodata_:
 * wmtsFunctions:KVP.GetTile.Valid.Tile.Transparency
 * wmtsFunctions:XML.GetTile.Valid.Tile.Transparency
 * wmtsFunctions:SOAP.GetTile.Valid.Tile.Transparency
 * wmtsFunctions:RESTful.GetTile.Valid.Tile.Transparency

All of them are selecting the tileMatrixSet identifier and tileMatrix identifier from the capabilities:
 1. read TileMatrixSet from the first TileMatrixSetLink
 1. select the TileMatrixSet with the name of 1.
 1. select the first TileMatrix from 2.
 1. select the identifier of 2.

The tileMatrixSet identifier (1.) and  tileMatrix identifier (4.) is used in the GetTile request. As style the default value _Default_style_ is used.

@vinnakota  Why do you thing the tileMatrixSet identifier is hard coded?  Have we overlooked something? 

-----
Detail out of the ctl-script wmtsFunctions.xml:
```
<xsl:variable name="layerId">TransparentNodata</xsl:variable>
<xsl:variable name="layer" select="$wmts.capabilities.doc/wmts:Contents/wmts:Layer[ows:Identifier = $layerId]"/>
<xsl:variable name="styleId">Default_style</xsl:variable>
<xsl:variable name="format">image/png</xsl:variable>
<xsl:variable name="tileMatrixSetId" select="$layer/wmts:TileMatrixSetLink[1]/wmts:TileMatrixSet"/>
<xsl:variable name="tileMatrixSet" select="$wmts.capabilities.doc/wmts:Contents/wmts:TileMatrixSet[ows:Identifier = $tileMatrixSetId]"/>
<xsl:variable name="tileMatrix" select="$tileMatrixSet/wmts:TileMatrix[1]"/>
<xsl:variable name="tileMatrixId" select="$tileMatrix/ows:Identifier"/>
```

**Comment by dstenger** [comment]
@vinnakota, can you please take a look at the previously given answer by lgoltz?

**Comment by dstenger** [comment]
@vinnakota Is there any update regarding this issue?

**Comment by vinnakota** [comment]
@dstenger apologies for the delayed response. I don't remember all the details and would need to retest this issue. Can we close this issue for now ?

**Comment by dstenger** [comment]
Sure, if the issue pops up again, we can reopen this issue.
