### ISSUE TITLE
Remove not approved profiles for 1.0

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wmts10#34]
The user should only be provide a field for Capabilities document.

No need to allow selection of profiles.

The GET binding profile should run by default. 

Need to remove or hide the other profiles from the beginning of the test (WMTS_ETS.xml file and config.xml)

**Comment by keshav-nangare** [comment]
Fixed with this commit: 07e9b589c87d365f17fd6a0af280109e578382b3

**Comment by bermud** [comment]
@keshav-nangare, I verified the commit. The RIs are passing and interface looks good. Thank you!
@dstenger, please verify an integrate the feature-issue#34 to master, as long with the other possible fixes, for the release this week.

**Comment by dstenger** [comment]
Following could be verified:
* GET binding profile is always run (by default).
* All other profiles are not executed any more.
Also, a functional test was successful.

PR was created: #35
and merged into master branch.
Tags are set and release notes are up to date.

**Comment by aaime** [comment]
Hi, I was hoping to validate a WMTS restful implementation via CITE tests but it seems that due to the work in this issue they are not getting run. May I ask why, I don't see the rationale.

**Comment by dstenger** [comment]
The other profiles have not been approved, yet.

If you are interested in the REST profile please create a new issue. We would be very happy if you can also provide a test service for the REST profile.
