### ISSUE TITLE
Update CTL with better information about conformance classes

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wmts10#36]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:
https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by lgoltz** [comment]
The specification does not define any conformance classes. 

The WMTS 1.0 ETS groups the tests into the following four groups:
* Common Operations 
* Get Capabilities 
* Get Tile 
* Get Feature Info

For each group it is possible (via Web GUI) to choose between executing
1. all
1. selected (single test can be selected by the user in the next step)
1. none

We have to decide if we want to specify conformance classes  (e.g. each group is one conformance class) and which are the basic conformance classes (as GetFeatureInfo is optional I think this should be Common Operations, Get Capabilities, Get Tile). 

Is the possibility to select single tests required? I would propose to remove this option and allow the user to select the defined conformance classes.
