### ISSUE TITLE
Create SoapUI tests and integrate them into Maven and Jenkinsfile

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wmts10#48]
See https://github.com/opengeospatial/ets-wms13/issues/56 for instructions.

Please use following service implementation: http://cite.deegree.org/deegree-webservices-3.4.0/services/wmts100?service=WMTS&request=GetCapabilities

**Comment by keshav-nangare** [comment]
The ets-wmts10 is based on the CTL so we can't execute this test-suite through the REST api.

**Comment by lgoltz** [comment]
#49 must be implemented first

**Comment by keshav-nangare** [comment]
Fixed with this PR https://github.com/opengeospatial/ets-wmts10/pull/51.
