### ISSUE TITLE
Enable Docker support and configure integration tests

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wmts10#52]
Please see:
* https://github.com/opengeospatial/cite/wiki/How-to-create-Docker-Images-of-test-suites
* https://github.com/opengeospatial/cite/wiki/How-to-run-tests-for-test-suites-with-SoapUI

**Comment by keshav-nangare** [comment]
Fixed with this PR #53.

**Comment by dstenger** [comment]
TODO: Update Docker TEAM Engine version to 5.4 when it has been released.

TEAM Engine 5.4 is required before merging this pull request.
After this pull request will have been merged:
- Create test job in Jenkins
- Create Docker Hub repository

**Comment by dstenger** [comment]
@keshav-nangare 
Build with `mvn clean install site -Pintegration-tests,docker` is currently failing (needs TEAM Engine version 5.4-SNAPSHOT).
Can you please check the SoapUI project? It should be similar to the one of WFS 2.0 test suite.

**Comment by keshav-nangare** [comment]
@dstenger 

Updated SoapUI Project and teamengine version to 5.4. The changes are pushed to the same PR.
