### ISSUE TITLE
Test wmts:Server.KVP.GET.InvalidQueryString is flawed

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wmts10#54]
The wmts:Server.KVP.GET.InvalidQueryString test throws a garbage query string at the WMTS GetCapabilities base URL and expects to get an ows:ExceptionReport back.  However, a WMTS GetCapabilities base URL isn't a complete URL to a WMTS service.  It needs a valid SERVICE=WMTS query parameter.  This mechanism allows multiple services (WMS, WMTS, WFS, WCS, etc.) to be handled by a single base URL.

Therefore, any test that uses a WMTS base URL without a SERVICE=WMTS query parameter isn't testing the WMTS service, and is therefore out of scope of the test suite.  The endpoint handler would have no way of knowing which service is being invoked.

**Comment by dstenger** [comment]
Thank you for reporting. We will check if the test can be adjusted according to your proposal (SERVICE=WMTS is existent).

**Comment by ghobona** [comment]
@keshav-nangare 

I agree with @pomakis that the test should include a SERVICE=WMTS query parameter.

**Comment by keshav-nangare** [comment]
Fixed with #64 PR.
