### ISSUE TITLE
Test wmts:Server.KVP.GET.InvalidRequest is flawed

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wmts10#56]
The wmts:Server.KVP.GET.InvalidRequest test makes a request with query parameters "service=WMTS&request=GetBOGUS" and expects to get an exception report back indicating "InvalidParameterValue".  However, WMTS 1.0 is bound by the OWS Common Implementation Specification (OGC 06-121r3), which states (in section 9.2.1) that "version" is a mandatory parameter.  Since this parameter is missing from the request, and since the interpretation of the other parameters (such as "request") may be sensitive to the WMTS version being invoked, the correct response to this request should be an exception report indicating "MissingParameterValue" (with location="version").  However, no specific type or version of the exception report can be expected, because these details are specified by the WMTS specification for the WMTS version being invoked, and without a specific version number in the request, the service may have no choice but to guess.  (E.g., a future WMTS 2.0 specification may be based on OWS Common 2.0, or even something completely different, so if a WMTS service that supports both WMTS 1.0 and WMTS 2.0 gets a bogus request without a "version" parameter, it could just as validly decide to return whatever exception report format is dictated by the WMTS 2.0 specification.)

The best way to fix this test is to simply add "version=1.0.0" to the request.

**Comment by dstenger** [comment]
Thank you for reporting. Is similar to #54 and #55 (however, in this case version parameter is considered).

**Comment by keshav-nangare** [comment]
@dstenger 

I agree with the **pomakis** suggestion in the first comment. I am attaching below reference from the documentation:
![Capture](https://user-images.githubusercontent.com/14732650/85388854-3fcd5600-b564-11ea-9aaf-f4aa1744dfe4.PNG)


I have executed the test suite by adding `version=1.0.0` to the request in the `InvalidRequest` method as per the proposed solution and it worked fine.

**Comment by keshav-nangare** [comment]
Fixed with this #62 PR.
