### ISSUE TITLE
https not supported

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wmts10#57]
The wmts:Server.KVP.GET.GetCapabilities.Response.OnlineResource test only accepts URL prefixes that start with "http://".  "https://" prefixes need to be accepted too.

**Comment by dstenger** [comment]
Thank you for reporting. We will check this behaviour. Can you provide a test service?

**Comment by pomakis** [comment]
Here's a test service:
https://demo.cubewerx.com/cubewerx/cubeserv/cite_wmts100/wmts/1.0.0/WMTSCapabilities.xml

**Comment by keshav-nangare** [comment]
Fixed with this commit: 6bf30f0bb5807ba2eb62987b9fe56a63616c9a26.

Now test will support prefix 'https://' too.
