### ISSUE TITLE
A GetCapabilities request should use "AcceptVersions", not "version"

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wmts10#59]
The wmts:Server.KVP.GET.GetCapabilities.Request.CaseInsensitive.KVP.Names test makes a request with a "version=1.0.0" parameter.  However, according to the OWS Common Implementation Specification (OGC 06-121r3), section 7.2.3, the GetCapabilities operation doesn't take a "version" parameter.  Instead, it takes an optional "AcceptVersions" parameter so that version negotiation can be performed.  So this test should be adjusted to make the request with "AcceptVersions=1.0.0"  rather than "version=1.0.0".

Also, most of the other wmts:Server.KVP.GET.GetCapabilities.* tests don't speficify any version number in the request.  This may work for now, since servers are currently unlikely to support any WMTS version other than 1.0.0.  However, when a new WMTS version comes out and servers start implementing it, these tests will all fail, because in the absense of an "AcceptVersion" parameter the services will be obligated to return a capabilities document corresponding to the new (latest) WMTS version, which these tests aren't for.  Since this test suite is specifically for WMTS 1.0.0, all GetCapabilities requests that it makes should include "AcceptVersions=1.0.0".

**Comment by dstenger** [comment]
Thank you for reporting. We will check the specification and come back to you.

**Comment by lgoltz** [comment]
`AcceptVersions=1.0.0` must be added to all GetCapabilities GET requests.

**Comment by keshav-nangare** [comment]
Following are the tests need to update: 

Missing version parameter:

```
wmts:Server.KVP.GET.InvalidQueryString
wmts:Server.KVP.GET.InvalidService
wmts:Server.KVP.GET.InvalidRequest

wmts:Server.KVP.GET.GetCapabilities.Request.Mandatory
wmts:Server.KVP.GET.GetCapabilities.Request.NoService
wmts:Server.KVP.GET.GetCapabilities.Request.InvalidService
wmts:Server.KVP.GET.GetCapabilities.Response.XML.Well.Formed
wmts:Server.KVP.GET.GetCapabilities.Response.SchemaReferenced
wmts:Server.KVP.GET.GetCapabilities.Response.SchemaValid
wmts:Server.KVP.GET.GetCapabilities.Response.AdvertisedFormat
wmts:Server.KVP.GET.GetCapabilities.Response.OnlineResource
wmts:Server.KVP.GET.GetCapabilities.Response.Encoding.Constraint
wmts:Server.KVP.GET.GetCapabilities.Response.Layer.Identifiers.Unique
wmts:Server.KVP.GET.GetCapabilities.Response.Layer.TileMatrixSet.Valid
wmts:Server.KVP.GET.GetCapabilities.Response.TileMatrixSet.Identifiers.Unique
wmts:Server.KVP.GET.GetCapabilities.Response.TileMatrix.Identifiers.Unique
wmts:Server.KVP.GET.GetCapabilities.Response.TileMatrixSet.ScaleDenominators.Unique

```

Using 'version' parameter:

`wmts:Server.KVP.GET.GetCapabilities.Request.CaseInsensitive.KVP.Names`

**Comment by keshav-nangare** [comment]
Updated all GetCapabilities request with a parameter "AcceptVersions".

Fixed with this commit: 5d9f3608047b84d45bd686f6fa06d50f8f3742b5  & PR: #61

**Comment by dstenger** [comment]
Thank you for the pull request.

However, isn't test `wmts:Server.KVP.GET.GetCapabilities.Request.CaseInsensitive.KVP.Names` still requested with `version` parameter. Can you please check this?

**Comment by keshav-nangare** [comment]
@dstenger 

I have updated the PR with new changes and it includes above test changes as well.

**Comment by lgoltz** [comment]
@keshav-nangare GetTile requests do not know ACCEPTVERSION. Requesting with VERSION is fine. Please revert commit https://github.com/opengeospatial/ets-wmts10/pull/61/commits/3eb93af807249ac1e836dd9710818f71fc997d72

**Comment by keshav-nangare** [comment]
@lgoltz 

I have removed ACCEPTVERSIONS parameters from GetTile and GetFeatureInfo test.

**Comment by mloskot** [comment]
By the way, the OGC 07-057r7 document also displays `version` in the `GetCapabilities` example:

![image](https://user-images.githubusercontent.com/80741/124091685-61ee9380-da56-11eb-9628-c80acc68d985.png)
