### ISSUE TITLE
Failing WMTS compliance test for capabilities that include RESTful operation URLs

### ISSUE THREAD

**Issue by robinhoutmeyers** [opengeospatial/ets-wmts10#79]
The test Server.KVP.GET.GetCapabilities.Response.OnlineResource verifies whether the capabilities response includes valid operation request URLs. This test currently expects that all these URLs end with ?, but this is not correct for RESTful urls.

The tested server is 
https://demo.luciad.com:443/LuciadFusionPlatform/ogc/wmts/wmts_test?&request=GetCapabilities&service=WMTS&AcceptVersions=1.0.0

As an example, the advertised URLs for the GetCapabilities operation are:
* KVP: https://demo.luciad.com:443/LuciadFusionPlatform/ogc/wmts/wmts_test?
* RESTful: https://demo.luciad.com:443/LuciadFusionPlatform/ogc/wmts/wmts_test/1.0.0/WMTSCapabilities.xml

I believe both are correct according to the OGC WMTS specification.

**Comment by dstenger** [comment]
Section 11.2 of [OGC 06-121r3](http://portal.opengeospatial.org/files/?artifact_id=20040) describes the following:
```
...
Thus, an HTTP GET URL prefix always ends in
either a question mark '?' or an ampersand '&'.
...
```
This is the reason why the test suite checks for the question mark.

However, the CITE team concluded that the OWS Common spec does not consider the option of providing RESTful OnlineResources.
So, we propose to update the test suite to check whether `ows:Value` element contains `RESTful`. If that is the case, the check for the question mark shall be dropped.

**Comment by dstenger** [comment]
@robinhoutmeyers The fix has been installed on Beta environment (https://cite.ogc.org/te2/). Can you please check if your problem is solved?

**Comment by robinhoutmeyers** [comment]
@dstenger Yes, I confirm this is now working as expected. Thanks!
