### ISSUE TITLE
Exponential notation sometimes used for row/col in GetTile requests

### ISSUE THREAD

**Issue by cmorriscmps** [opengeospatial/ets-wmts10#85]
For layers that support large tile matrices with MatrixWidth >= 1000000 and/or MatrixHeight >= 1000000, Test wmts:Server.KVP.GET.GetTile.Mandatory may construct GetTile requests using exponential notation for row or col values.  While exponential notation is acceptable in the context of floating point numbers, it is not a valid encoding for integers (per sec 3.3.13 of XML Schema part 2: Datatypes, https://www.w3.org/TR/xmlschema-2/#integer).

![image](https://github.com/opengeospatial/ets-wmts10/assets/64432570/383f4c87-07a8-4d19-963a-5a360744e846)

**Comment by dstenger** [comment]
Thank you for providing the pull request.
