### ISSUE TITLE
text\plain causes error in RESTful valid infoformat test

### ISSUE THREAD

**Issue by matsoo** [opengeospatial/ets-wmts10#9]
In the wmts:Server.RESTful.GetFeatureInfo.Valid.InfoFormat test text/plain (and possibly other non-XLM formats) does not seem to be handled correctly. Using text/plain with some none XML-like text causes the following error:
Fatal Error: Error reported by XML parser; Line#: 1; Column#: 1
Error: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

text/html however works even when it is not valid XML. Tested on beta site in r4.

**Comment by dbretschneider** [comment]
@matsoo 
I don't know what's the current state. Does the error message occurs with the actual version of the ```ets-wmts10```?

**Comment by matsoo** [comment]
@dbretschneider 
This tests on the beta site now seems to work properly (test version 0.5). I don't have a local TEAM Engine setup at the moment so I have not checked if there is a later version than that.

**Comment by bermud** [comment]
@matsoo 
The latest version of the test is 0.5. Will close this issue. 
Is your application passing all the tests? We need first implementers to move the test suite through the OGC process and get it approved.
