### ISSUE TITLE
Some GetCapabilities requests do not specify version 1.0.0

### ISSUE THREAD

**Issue by cmorriscmps** [opengeospatial/ets-wmts10#90]
The wmts:Server.KVP.GET.GetCapabilities.Request.Sections.* tests do not include an acceptVersions parameter.  Although the parameter is optional because servers may support multiple versions, it must be included in these tests to make sure that they are testing version 1.0.0.

**Comment by dstenger** [comment]
Thank you for reporting.
Yes, this is a well known problem.
We will review your pull request soon.

**Comment by dstenger** [comment]
A functional test with the reference implementation was successful.

@cmorriscmps Can you please check my comments in https://github.com/opengeospatial/ets-wmts10/pull/92 regarding the code?
