### ISSUE TITLE
Test wmts:Server.KVP.GET.GetCapabilities.Response.TileMatrixSet.WellKnownScaleSet is too strict

### ISSUE THREAD

**Issue by cmorriscmps** [opengeospatial/ets-wmts10#91]
There are several issues with wmts:Server.KVP.GET.GetCapabilities.Response.TileMatrixSet.WellKnownScaleSet

The test fails if the server advertises any WellKnownScaleSets other than GlobalCRS84Scale, GlobalCRS84Pixel, GoogleCRS84Quad, or GoogleMapsCompatible.  It should just accept any WellKnownScaleSets other than these without checking them any farther.

The test also fails if the server implements one of these scale sets to a level that differs from the one it recognizes.  Servers should be free to implement the scale set to any level.

The test will also fail if the scale denominators differ at all.  It should allow for small differences in rounding the numbers.

**Comment by dstenger** [comment]
Thanks for reporting and providing the pull request.
We will review it soon.

**Comment by dstenger** [comment]
Spec (OGC 07-057r7) says:
```
11.2 A standard set of scales
It is strongly recommended that WMTS servers offer their Layers using, where possible,
the well-known scale sets defined in the Annex E and reference them in the service
metadata document in the TileMatrixSetDef section. This would aid interoperability
between systems and allow users to "mash-up" suitable services.
```

Although it is a strong recommendation, I am fine to make the test suite lax here as this is no requirement.

**Comment by dstenger** [comment]
A functional test with the reference implementation was successful.
